#! /bin/bash

#SBATCH --ntasks=1

## default 24 threads.
##SBATCH --cpus-per-task=2

## More than 128G
##SBATCH --mem=512000

#SBATCH --job-name="macse"
#SBATCH --output=%j_macse.log
#BATCH --exclude=node117,node118

java -jar ../../../macse_v2.07.jar -prog enrichAlignment -align alpha_nn_10_nt_alignment.fasta -seq ES_alpha_skin_slime.fasta
